### ISSUE TITLE
Bounding boxes empty in the new dataset

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [AutoNUE/public-code#5]
Hi,

I was trying to generate instance labels for the new release (part 2) of the IDD. However, I observed that polygons in the json file for certain classes do not have any coordinates (i.e. the labelled bounding boxes are empty) which keeps giving an error. I didn't face such error in the first part of the dataset. 

Please suggest some workaround for this issue.

Thanks.

**Comment by jaswanth-adas** [comment]
Hi Anirudh,
Got similar error. Found one while using part 2 data set.  Issue is with following file as annotations are missing for category pole.

idd2_1\gtFine\train\283\frame2890_gtFine_polygons.json

 {
            "date": "08-Feb-2019 12:43:50", 
            "deleted": 0, 
            "draw": true, 
            "id": 4, 
            "label": "pole", 
            **"polygon": [],**  can see this..........................
            "user": "cvit", 
            "verified": 0
        }, 

In part-1 dataset I didnot get any issue while converting to masks. 



Coming to part-3 released recently, it also have similar issue while generating masks (gtFine_labelTrainIds)

error got at file:
 IDD_Part3\gtFine\train\452\0003438_gtFine_polygons.json
category vegetation have no polygon points in json annotation file as shown below...
  {
            "date": "12-Jul-2019 21:16:50", 
            "deleted": 0, 
            "draw": true, 
            "id": 6, 
            "label": "vegetation", 
            "polygon": [], 
            "user": "cvit", 
            "verified": 0
        },


Please suggest me how to work further with data set part-2 and 3. Thank you.

**Comment by anirudh-chakravarthy** [comment]
I think the new commit has solved this.
