### ISSUE TITLE
Sample input and output of instance segmentation evaluation script

### ISSUE THREAD

**Issue by kHarshit** [AutoNUE/public-code#6]
The `evaluate_instance_segmentation.py` takes input defined as follows:

https://github.com/AutoNUE/public-code/blob/b2d44a4b7b05b66b05af68dbc35af058235f24ea/evaluation/evaluate_instance_segmentation.py#L13-L29

Do multiple files need to be created (one for each label) per image?

Can you provide such sample file for validation images in the dataset so as to check the working of the script. Or for at least one image?  Or tell me how do I generate such file from `*_gtFine_instanceids.png`?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I was facing the same issue. For instance segmentation, I am unable to create text files containing the predictions of the given format. Were you able to generate text files?

**Comment by kHarshit** [comment]
Hi @anirudh-chakravarthy ,

AFAIK, you need to create separate binary mask file for each predicted instance. You can save those masks from the model you're using.

![car](https://user-images.githubusercontent.com/20869671/65231612-6d750280-daed-11e9-90cb-04f53463f3c8.png)
